### PR TITLE
Addition of asistencia-backend as a submodule

### PR DESCRIPTION
**Pull request by CarloGauss33**
## Type
Enhancement

___

## Description
This PR introduces a new submodule to the project. The asistencia-backend has been added as a submodule, which will allow for better modularity and separation of concerns in the project. The submodule is linked to its repository at https://github.com/open-source-uc/asistencia-backend.

___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>.gitmodules&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        .gitmodules<br><br>
        <strong>The .gitmodules file has been updated to include the <br>asistencia-backend as a submodule. The path and URL for the <br>submodule have been specified.</strong>
      </ul>
    </details>
  </td>
  <td><a href="https://github.com/open-source-uc/asistencia/pull/15/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584"> +3/-0</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by CarloGauss33** [comment]
Preparing PR description...

**Comment by CarloGauss33** [comment]
**[PR Description](https://github.com/open-source-uc/asistencia/pull/15)** updated to latest commit (https://github.com/open-source-uc/asistencia/commit/aa20ef1241cc799bdd1805794db10c37e45588a9)

**Comment by CarloGauss33** [comment]
Preparing review...

**Comment by CarloGauss33** [comment]
## PR Analysis

- 🎯 **Main theme:** Addition of a new submodule
- 📝 **PR summary:** This PR introduces the 'asistencia-backend' as a new submodule to the project, aiming to improve modularity and separation of concerns. The submodule is linked to its repository at https://github.com/open-source-uc/asistencia-backend.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 1, because the PR only involves the addition of a submodule, which is a straightforward change.
- 🔒 **Security concerns:** No
## PR Feedback

- 💡 **General suggestions:** The addition of a submodule is a good practice for separating concerns and improving modularity. However, it would be beneficial to include a README file in the submodule repository explaining its purpose and how it interacts with the main project.


- <details><summary> 🤖 Code feedback:</summary></details>

**Review by benjavicente — APPROVED** [review]

**Pull request merged**
